### ISSUE TITLE
Unable to use privileged=true on Autopilot

### ISSUE THREAD

**Issue by bourquep** [bil/gitlab-executor-gke-autopilot#1]
When I try to install the gitlab-runner with `privileged: true`, I get the following error:

```
GKE Warden rejected the request because it violates one or more constraints.
Violations details: {"[denied by autogke-disallow-privilege]":["container gitlab-runner is privileged; not allowed in Autopilot"]}
```

Were you able to deal with this?

**Comment by bil-paul** [comment]
As [documented](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-security#autopilot-pss), privileged containers are not supported in GKE Autopilot.

The documentation for this project does not change the default parameter of [privileged : false](https://gitlab.com/gitlab-org/charts/gitlab-runner/-/blob/main/values.yaml#L444).

For privileged containers, use GKE standard, not Autopilot. This is outside the scope of this project, so the documentation here may not apply.
